name: conditionals
on: [push]
jobs:
 regular_job:
 ## to specify the branch name
   if: ${{ github.ref != 'refs/heads/main' }}
   runs-on: ubuntu-latest
   steps:
     - run: echo "Regular job"   
 special_job:
   if: contains( github.ref, 'main')
   runs-on: ubuntu-latest
   steps:
     - run: |
          OUTPUT= `aws ec2 describe-instances \
          --filters Name=instance-type,Values=t2.micro \
          --query Reservations[*].Instances[*].[InstanceId] \
          --output text`





