# this is the work flow name
# name: setup-node
# name: manual
name: scheduled

# this is the trigger

################################### MANUAL TRIGGER#############################################
# MANUAL TRIGGER
# on:
#   workflow_dispatch:
#     inputs:
#       name:
#         description: The name to echo
#         default: World
#         required: false
##############################################################################################


################################### SCHEDULE TRIGGER ########################################
on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - run: echo This job runs every 1 minutes
##############################################################################################




## on the push to the branch it runs the jobs below

## the jobs runs on a runner(runs-on) which is a container to be specified eg ubuntu-lastest


# jobs:
#   setup-node:
#     runs-on: ubuntu-latest

#     ### each job has steps(line 22 , 23) and actions(18,19)
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: '14'
#       - run: npm -v
#       - run: node -v