





################################### MANUAL TRIGGER#############################################

# this is the work flow name
name: MANUAL

# this is the trigger
on:
  workflow_dispatch:
    inputs:
      name:
        description: The name to echo
        default: World
        required: false

# THESE ARE JOBS WHICH CONTAINS ACTIONS / STEPS
jobs:
  manual:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ github.event.inputs.name }}"
##############################################################################################


################################### SCHEDULE TRIGGER ########################################
# name: scheduled

# this is the trigger
# on:
#   schedule:
#     - cron: '*/1 * * * *'

# THESE ARE JOBS WHICH CONTAINS ACTIONS / STEPS
# jobs:
#   scheduled:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo This job runs every 1 minutes
##############################################################################################








################################### SETUP NODE ON PUSH ########################################
# name: setup-node


## the jobs runs on a runner(runs-on) which is a container to be specified eg ubuntu-lastest
# on: [push]


# jobs:
#   setup-node:
#     runs-on: ubuntu-latest

#     ### each job has steps(line 22 , 23) and actions(18,19)
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: '14'
#       - run: npm -v
#       - run: node -v
##############################################################################################