# name: variables-secrets
# on:
#   push:
#     branches:
#       - main
#  #### PIPELINE/WORKFLOW LEVEL ENVIRONMENT VARIABLE GLOBAL TO ALL JOBS AND STEPS
# env:
#   baz_variable: BAZ

# jobs:
#   variables-secrets-1:
#     runs-on: ubuntu-latest
#     env:
#     #### JOB LEVEL ENVIRONMENT VARIABLE LOCAL TO THE JOB
#       bar_variable: BAR
#     steps:
#       - name: Retrieve secret via an env var
#         env:
#           example_api_key: ${{ secrets.SECRET }}
#           ### THIS IS A STEP LEVEL ENVIRONMENT VARIABLE LOCAL TO THIS STEP
#           foo_variable: FOO
#         run: echo "$example_api_key $foo_variable $baz_variable"
#       - name: Directly retrieve a secret
#         run: echo "${{ secrets.SECRET }} $bar_variable"
#   variables-secrets-2:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Retrieve global env var
#         ### ONLY BAZ IS PRINTED OUT AS ITS  A GLOBAL VARIABLE
#         run: echo "$baz_variable $bar_variable $foo_variable"